### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by pescerosso** [harbur/guestbook-example#2]
I am getting this infinite loop of errors when running:

Creating guestbookexamplemaster_redismaster_1
Creating guestbookexamplemaster_redisslave_1
Creating guestbookexamplemaster_guestbook_1
Attaching to guestbookexamplemaster_redismaster_1, guestbookexamplemaster_redisslave_1, guestbookexamplemaster_guestbook_1
redismaster_1  | 1:C 02 May 00:56:07.057 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redisslave_1   |                 _._                                                  
redisslave_1   |            _.-``__ ''-._                                             
redisslave_1   |       _.-``    `.  `_.  ''-._           Redis 2.8.19 (00000000/0) 64 bit
redisslave_1   |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redisslave_1   |  (    '      ,       .-`  | `,    )     Running in stand alone mode
redisslave_1   |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redisslave_1   |  |    `-._   `._    /     _.-'    |     PID: 7
redisslave_1   |   `-._    `-._  `-./  _.-'    _.-'                                   
redisslave_1   |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redisslave_1   |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redisslave_1   |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redismaster_1  |                 _._                                                  
guestbook_1    | [negroni] listening on :3000
redisslave_1   |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redismaster_1  |            _.-``__ ''-._                                             
redisslave_1   |  |    `-._`-._        _.-'_.-'    |                                  
redismaster_1  |       _.-``    `.  `_.  ''-._           Redis 3.2.8 (00000000/0) 64 bit
redisslave_1   |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redismaster_1  |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redisslave_1   |       `-._    `-.__.-'    _.-'                                       
redismaster_1  |  (    '      ,       .-`  | `,    )     Running in standalone mode
redisslave_1   |           `-._        _.-'                                           
redismaster_1  |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redisslave_1   |               `-.__.-'                                               
redismaster_1  |  |    `-._   `._    /     _.-'    |     PID: 1
redisslave_1   | 
redismaster_1  |   `-._    `-._  `-./  _.-'    _.-'                                   
redismaster_1  |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redismaster_1  |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redisslave_1   | [7] 02 May 00:56:07.909 # Server started, Redis version 2.8.19
redismaster_1  |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redismaster_1  |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redismaster_1  |  |    `-._`-._        _.-'_.-'    |                                  
redismaster_1  |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redismaster_1  |       `-._    `-.__.-'    _.-'                                       
redismaster_1  |           `-._        _.-'                                           
redisslave_1   | [7] 02 May 00:56:07.912 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redismaster_1  |               `-.__.-'                                               
redisslave_1   | [7] 02 May 00:56:07.912 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redismaster_1  | 
redisslave_1   | [7] 02 May 00:56:07.912 * The server is now ready to accept connections on port 6379
redismaster_1  | 1:M 02 May 00:56:07.059 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redismaster_1  | 1:M 02 May 00:56:07.059 # Server started, Redis version 3.2.8
redismaster_1  | 1:M 02 May 00:56:07.059 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redismaster_1  | 1:M 02 May 00:56:07.059 * The server is now ready to accept connections on port 6379
redisslave_1   | [7] 02 May 00:56:08.912 * Connecting to MASTER redis-master:6379
redisslave_1   | [7] 02 May 00:56:08.913 * MASTER <-> SLAVE sync started
redisslave_1   | [7] 02 May 00:56:08.913 * Non blocking connect for SYNC fired the event.
redisslave_1   | [7] 02 May 00:56:08.913 * Master replied to PING, replication can continue...
redismaster_1  | 1:M 02 May 00:56:08.914 * Slave 172.17.0.3:6379 asks for synchronization
redismaster_1  | 1:M 02 May 00:56:08.914 * Full resync requested by slave 172.17.0.3:6379
redismaster_1  | 1:M 02 May 00:56:08.914 * Starting BGSAVE for SYNC with target: disk
redismaster_1  | 1:M 02 May 00:56:08.914 * Background saving started by pid 14
redisslave_1   | [7] 02 May 00:56:08.914 * Partial resynchronization not possible (no cached master)
redisslave_1   | [7] 02 May 00:56:08.914 * Full resync from master: 45ef021a6b4095e04f49b4afd812c5d491955fce:1
redismaster_1  | 14:C 02 May 00:56:08.939 * DB saved on disk
redismaster_1  | 14:C 02 May 00:56:08.939 * RDB: 0 MB of memory used by copy-on-write
redismaster_1  | 1:M 02 May 00:56:08.972 * Background saving terminated with success
redisslave_1   | [7] 02 May 00:56:08.972 * MASTER <-> SLAVE sync: receiving 76 bytes from master
redisslave_1   | [7] 02 May 00:56:08.972 * MASTER <-> SLAVE sync: Flushing old data
redisslave_1   | [7] 02 May 00:56:08.972 * MASTER <-> SLAVE sync: Loading DB in memory
redisslave_1   | [7] 02 May 00:56:08.972 # Can't handle RDB format version 7
redisslave_1   | [7] 02 May 00:56:08.972 # Failed trying to load the MASTER synchronization DB from disk
redismaster_1  | 1:M 02 May 00:56:08.972 * Synchronization with slave 172.17.0.3:6379 succeeded
redismaster_1  | 1:M 02 May 00:56:08.973 # Connection with slave 172.17.0.3:6379 lost.
redisslave_1   | [7] 02 May 00:56:09.923 * Connecting to MASTER redis-master:6379
redisslave_1   | [7] 02 May 00:56:09.924 * MASTER <-> SLAVE sync started
redisslave_1   | [7] 02 May 00:56:09.924 * Non blocking connect for SYNC fired the event.
redisslave_1   | [7] 02 May 00:56:09.925 * Master replied to PING, replication can continue...
redisslave_1   | [7] 02 May 00:56:09.925 * Partial resynchronization not possible (no cached master)
redismaster_1  | 1:M 02 May 00:56:09.925 * Slave 172.17.0.3:6379 asks for synchronization
redismaster_1  | 1:M 02 May 00:56:09.925 * Full resync requested by slave 172.17.0.3:6379
redismaster_1  | 1:M 02 May 00:56:09.925 * Starting BGSAVE for SYNC with target: disk
redismaster_1  | 1:M 02 May 00:56:09.926 * Background saving started by pid 15
redisslave_1   | [7] 02 May 00:56:09.926 * Full resync from master: 45ef021a6b4095e04f49b4afd812c5d491955fce:1
redismaster_1  | 15:C 02 May 00:56:09.950 * DB saved on disk
redismaster_1  | 15:C 02 May 00:56:09.951 * RDB: 0 MB of memory used by copy-on-write
redismaster_1  | 1:M 02 May 00:56:09.991 * Background saving terminated with success
redismaster_1  | 1:M 02 May 00:56:09.991 * Synchronization with slave 172.17.0.3:6379 succeeded
redismaster_1  | 1:M 02 May 00:56:09.992 # Connection with slave 172.17.0.3:6379 lost.
redisslave_1   | [7] 02 May 00:56:09.991 * MASTER <-> SLAVE sync: receiving 76 bytes from master
redisslave_1   | [7] 02 May 00:56:09.991 * MASTER <-> SLAVE sync: Flushing old data
redisslave_1   | [7] 02 May 00:56:09.991 * MASTER <-> SLAVE sync: Loading DB in memory
redisslave_1   | [7] 02 May 00:56:09.992 # Can't handle RDB format version 7
redisslave_1   | [7] 02 May 00:56:09.992 # Failed trying to load the MASTER synchronization DB from disk
redisslave_1   | [7] 02 May 00:56:10.937 * Connecting to MASTER redis-master:6379
redisslave_1   | [7] 02 May 00:56:10.937 * MASTER <-> SLAVE sync started
redisslave_1   | [7] 02 May 00:56:10.937 * Non blocking connect for SYNC fired the event.
redisslave_1   | [7] 02 May 00:56:10.937 * Master replied to PING, replication can continue...
redisslave_1   | [7] 02 May 00:56:10.938 * Partial resynchronization not possible (no cached master)
redismaster_1  | 1:M 02 May 00:56:10.938 * Slave 172.17.0.3:6379 asks for synchronization
redismaster_1  | 1:M 02 May 00:56:10.939 * Full resync requested by slave 172.17.0.3:6379
redismaster_1  | 1:M 02 May 00:56:10.939 * Starting BGSAVE for SYNC with target: disk
redismaster_1  | 1:M 02 May 00:56:10.939 * Background saving started by pid 16
redisslave_1   | [7] 02 May 00:56:10.939 * Full resync from master: 45ef021a6b4095e04f49b4afd812c5d491955fce:1
redismaster_1  | 16:C 02 May 00:56:10.958 * DB saved on disk
redismaster_1  | 16:C 02 May 00:56:10.958 * RDB: 0 MB of memory used by copy-on-write
redismaster_1  | 1:M 02 May 00:56:11.005 * Background saving terminated with success
redismaster_1  | 1:M 02 May 00:56:11.006 * Synchronization with slave 172.17.0.3:6379 succeeded
redisslave_1   | [7] 02 May 00:56:11.005 * MASTER <-> SLAVE sync: receiving 76 bytes from master
redisslave_1   | [7] 02 May 00:56:11.006 * MASTER <-> SLAVE sync: Flushing old data
redisslave_1   | [7] 02 May 00:56:11.006 * MASTER <-> SLAVE sync: Loading DB in memory
redismaster_1  | 1:M 02 May 00:56:11.006 # Connection with slave 172.17.0.3:6379 lost.
redisslave_1   | [7] 02 May 00:56:11.006 # Can't handle RDB format version 7
redisslave_1   | [7] 02 May 00:56:11.006 # Failed trying to load the MASTER synchronization DB from disk
redisslave_1   | [7] 02 May 00:56:11.946 * Connecting to MASTER redis-master:6379
redisslave_1   | [7] 02 May 00:56:11.947 * MASTER <-> SLAVE sync started
redisslave_1   | [7] 02 May 00:56:11.947 * Non blocking connect for SYNC fired the event.
redisslave_1   | [7] 02 May 00:56:11.948 * Master replied to PING, replication can continue...
redisslave_1   | [7] 02 May 00:56:11.948 * Partial resynchronization not possible (no cached master)
redismaster_1  | 1:M 02 May 00:56:11.949 * Slave 172.17.0.3:6379 asks for synchronization
redismaster_1  | 1:M 02 May 00:56:11.949 * Full resync requested by slave 172.17.0.3:6379
redismaster_1  | 1:M 02 May 00:56:11.949 * Starting BGSAVE for SYNC with target: disk
redismaster_1  | 1:M 02 May 00:56:11.950 * Background saving started by pid 17
redisslave_1   | [7] 02 May 00:56:11.950 * Full resync from master: 45ef021a6b4095e04f49b4afd812c5d491955fce:1
redismaster_1  | 17:C 02 May 00:56:11.970 * DB saved on disk
redismaster_1  | 17:C 02 May 00:56:11.971 * RDB: 0 MB of memory used by copy-on-write
redismaster_1  | 1:M 02 May 00:56:12.014 * Background saving terminated with success
redismaster_1  | 1:M 02 May 00:56:12.015 * Synchronization with slave 172.17.0.3:6379 succeeded
redisslave_1   | [7] 02 May 00:56:12.015 * MASTER <-> SLAVE sync: receiving 76 bytes from master
redisslave_1   | [7] 02 May 00:56:12.015 * MASTER <-> SLAVE sync: Flushing old 

docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by dkapanidis** [comment]
Fixed, the master `redis` image was pointing to latest which is now different than the slave, thus creating the infinity loop.

change was here: https://github.com/harbur/guestbook-example/blob/master/docker-compose.yml#L9
